# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
                ('process_number', models.TextField(blank=True, null=True, verbose_name='Número do processo')),
                ('version_stable', models.CharField(default='-', max_length=15, verbose_name='Versão estável')),
                ('licenses_number', models.CharField(default='-', max_length=25, verbose_name='Número de licensas')),
                ('license_validity', models.CharField(default='Perpétua', max_length=25, verbose_name='Vigência da licença')),
                ('note', models.TextField(verbose_name='Obserçaões')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Categoria')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Provider', verbose_name='Fornecedor')),
            ],
        ),
    ]
