# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170818_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='products',
            field=models.ManyToManyField(to='catalog.Software', verbose_name='softwares'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('Cuidado', 'Cuidado'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=7, verbose_name='Gravidade'),
        ),
    ]
