# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170821_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
            },
        ),
        migrations.RemoveField(
            model_name='software',
            name='license_validity',
        ),
    ]
