# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170823_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.License', verbose_name='Licença'),
        ),
    ]
