# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_software_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_at', models.DateTimeField(auto_now_add=True, verbose_name='Corrigido em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Vulnerability', verbose_name='Vulnerabilidade')),
            ],
            options={
                'verbose_name': 'Quem corrigiu',
            },
        ),
    ]
