# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_remove_whofixed_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='fixed',
            field=models.ManyToManyField(through='catalog.WhoFixed', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
        migrations.AddField(
            model_name='whofixed',
            name='vulnerability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Vulnerability', verbose_name='Vulnerabilidade'),
            preserve_default=False,
        ),
    ]
