# Generated by Django 2.2.3 on 2019-07-05 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20171117_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
